name: Flutter Build for Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
        name: Setup Java
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'
        name: Setup Flutter
      - run: echo $KEY_JKS > upload-keystore.jks && flutter pub get && flutter build appbundle --release
        name: Run Build
      - uses: actions/upload-artifact@v2
        with:
          name: release-appbundle
          path: "build/app/outputs/bundle/release/app-release.aab"
        name: Save build output
